export const Amenities = {
  WASHER: "WASHER",
  DRYER: "DRYER",
  DISHWASHER: "DISHWASHER",
  AIR_CONDITIONING: "AIR_CONDITIONING",
  HEATING: "HEATING",
  INTERNET: "INTERNET",
  CABLE_TV: "CABLE_TV",
  FREE_PARKING: "FREE_PARKING",
  GYM: "GYM",
  POOL: "POOL",
  HOT_TUB: "HOT_TUB",
  KITCHEN: "KITCHEN",
};
